# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StoreFood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StoreFood
pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'CHTCollectionViewWaterfallLayout/Swift'
  pod 'Firebase'
  pod 'Firebase/Storage'
  pod 'DropDown'
  pod 'SwipeCellKit'
 pod 'ActionSheetPicker-3.0'
  pod 'JGProgressHUD'

end
